### PR TITLE
Operation refactor (part 1)

### PR DESCRIPTION
**Pull request by giannissc**
I am introducing Tool and Spindle changes to the Fluent API and all the necessary tests

In Part 2 I will be introducing Feed changes. This is going to be messier so I opted for breaking them into 2 PR.

### CODE REVIEW

**Comment by giannissc** [comment]
SonarCloud is raising duplication errors on the test strings. Should I try to fix? @voneiden

**Comment by voneiden** [comment]
The duplication errors are for the four last tests which share a very similar structure.  If you want to get your hands dirty, check out parametrization @ https://docs.pytest.org/en/6.2.x/parametrize.html

You could parametrize the tool(s) and expected outputs and have a single test.

The test string code smell nags are because there are no line breaks but the strings are broken into multiple string sections, like 

 ```python
x = ("foo" "bar")
```

vs

```python
x = ("foo"
     "bar")
```

It's also not necessary to always test full gcode output - in fact testing only within the scope of the test would be preferable in this case. Makes the test less fragile to noise.

**Comment by giannissc** [comment]
The test string is modified by black so If I add the line then black check will fail

**Comment by giannissc** [comment]
Can I parametrize across test files. test_pocket, test_profile and test_drill they same the exact same thing. The operation that happens is irrelevant since we are just checking what gets added between operation. Where should I include such a test? A new test_tool_change file? @voneiden

**Comment by voneiden** [comment]
My bad. Maybe that can be resolved by adding a comment on the first line, then black shouldn't be able to touch the line breaks:

```python
x = (
    # black
    "foo"
    "bar"
)
```

L

**Comment by voneiden** [comment]
New file is fine and perhaps the operation can be one parameter of the test.

**Comment by giannissc** [comment]
Ready! @voneiden

**Review by voneiden — APPROVED** [review]
Looks good, thank you.

**Pull request merged**
