### PR TITLE
Command refactor

### PR DESCRIPTION
**Pull request by giannissc**
I did the rebase in a new branch to make my life easier. Here are all the changes apart from the `kwargs`

### CODE REVIEW

**Comment by giannissc** [comment]
I rebased onto your most recent changes and I noticed that test_fluent is failing now. Can you think of a reason why?

**Comment by giannissc** [comment]
I have modified the test_fluent but I don't know if it's something you missed and if I am doing it correctly @voneiden

**Comment by voneiden** [comment]
Hmm yes, [6a23c4d](https://github.com/voneiden/cq-cam/pull/35/commits/6a23c4df26bc88c25d0577f3b144f3d189df377e) is redundant, the issue is here

https://github.com/voneiden/cq-cam/pull/35/commits/39202e7db3b42d14bbe8627174098a87e9bc6d93#diff-5188ac39903770f07f01f12be960497b41b697906e6d94cd9a7649a93bb75e96L234

Seems like you may have accidentally removed some change to `show` method I introduced here recently in https://github.com/voneiden/cq-cam/pull/31 ? Otherwise this is good to go. 



edit: other things too, like the tool_radius property @ https://github.com/voneiden/cq-cam/pull/35/files#diff-5188ac39903770f07f01f12be960497b41b697906e6d94cd9a7649a93bb75e96L280

**Comment by voneiden** [comment]
Besides that, looks like the rebase went well. There's one code smell reported by sonar but it's quite trivial (`Union` vs `|`), no need to take any action for now.

The failing test is a good case example on why it's important to first establish why a test is failing before deciding how to resolve it. Modifying the test (or even deleting it) should only be considered after it has been established that the failure is to be expected as a result of the changes that have been previously made.

It also highlights well how a test can sometimes prevent an unintended side effect from ending up into production. 

> I did the rebase in a new branch to make my life easier. 

Perfectly fine, if not even recommendable. Keeping your development work on feature branches instead of the main branch makes it easier to work on multiple unrelated things at the same time.

**Comment by giannissc** [comment]
> The failing test is a good case example on why it's important to first establish why a test is failing before deciding how to resolve it. Modifying the test (or even deleting it) should only be considered after it has been established that the failure is to be expected as a result of the changes that have been previously made.

It was a happy coincidence that you fixed ocp-vscode issues before I merged and were able to detect this

**Comment by giannissc** [comment]
LGTM @voneiden

**Review by voneiden — APPROVED** [review]
Thanks! LGTM, onwards to new challenges!

**Pull request merged**
